### ISSUE TITLE
Pergunta

### ISSUE THREAD

**Issue by israel-bastos** [josefilho/CFN_API#1]
Opa, tudo na paz? Essa API é sua?  Estou fazendo uma pesquisa e me deparei com ela, mas a requisição para o endpoint tá dando 404.

Foi mal, tive que abrir uma issue porque não consegui mandar mensagem de outra maneira.

**Comment by grejc** [comment]
Tudo na paz, eu desenvolvi essa API já faz um bom tempo e atualmente está descontinuada, pois não achei um local adequado para fazer deploy infelizamente. Desculpe a demora pela resposta.
